from .blog import blog
from .contact import ContactFormView
from .category import CategoryListView
from .myArticles import myArticles
from .articlePage import ArticleView
from .createPost import CreatePostView
from .updatePost import UpdatePostView
from .deletePost import DeletePostView
from .deleteComment import deleteComment
